(()=>{
'use strict';
const THEME_KEY='musicFilesThemeV1',TOUR_KEY='musicFilesOnboardingV1';let theme=localStorage.getItem(THEME_KEY)||'dark',tour=null,step=0;
const css=document.createElement('style');css.textContent=`:root{--guide-red:#e53935}.game-tools{position:fixed;top:58px;right:18px;z-index:120;display:flex;gap:6px}.game-tool{border:1px solid #46525d;background:rgba(10,14,18,.96);color:#eef2f5;padding:7px 10px;border-radius:6px;cursor:pointer;font:700 .76rem "Segoe UI",Tahoma,Arial,sans-serif;box-shadow:0 7px 24px rgba(0,0,0,.22)}html[data-theme="light"] body{background:#eef1f3!important;color:#1e252b!important}html[data-theme="light"] .game-tool{background:#fff;color:#1e252b;border-color:#8d979f}.tour-target-parent{outline:4px solid var(--guide-red)!important;outline-offset:4px!important;box-shadow:0 0 0 7px rgba(229,57,53,.18)!important}.tour-box{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:200;width:min(520px,calc(100vw - 24px));background:#12171c;color:#f5f7f8;border:2px solid var(--guide-red);border-radius:10px;padding:14px 15px;box-shadow:0 18px 60px rgba(0,0,0,.46);font-family:"Segoe UI",Tahoma,Arial,sans-serif}.tour-box strong{display:block;color:#ff9b98;margin-bottom:5px}.tour-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:10px}.tour-actions button{border:1px solid #66717a;background:#252d34;color:#fff;padding:6px 10px;border-radius:5px;cursor:pointer}.tour-actions .next{border-color:#ff6b67}.tour-count{float:left;color:#aeb7bd;font-size:.75rem;margin-top:8px}html[data-theme="light"] .desktop-qr{background:rgba(255,255,255,.97)!important;color:#1e252b!important;border-color:#8d979f!important}html[data-theme="light"] .desktop-qr span{color:#59636b!important}@media(max-width:850px){.game-tools{top:46px;right:6px}.game-tool{font-size:.68rem;padding:6px 7px}.tour-box{bottom:72px}}`;document.head.appendChild(css);
const tools=document.createElement('div');tools.className='game-tools';tools.id='gameTools';tools.innerHTML='<button class="game-tool" id="tourBtn" type="button">? Οδηγός</button><button class="game-tool" id="themeBtn" type="button"></button>';document.body.appendChild(tools);const themeBtn=document.getElementById('themeBtn');
function innerCSS(){return `.action-required,.tour-target-inner{outline:4px solid #e53935!important;outline-offset:3px!important;border-color:#e53935!important;box-shadow:0 0 0 7px rgba(229,57,53,.18),0 0 20px rgba(229,57,53,.35)!important;animation:guidePulse 1.25s ease-in-out infinite!important}.prompt.action-required{color:#ff7772!important}.controls .action-required{padding:3px 6px!important;border-radius:5px!important;background:rgba(229,57,53,.12)!important}@keyframes guidePulse{50%{box-shadow:0 0 0 3px rgba(229,57,53,.12),0 0 8px rgba(229,57,53,.22)}}html[data-game-theme="light"],html[data-game-theme="light"] body{background:#eef1f3!important;color:#1d252b!important;color-scheme:light!important}html[data-game-theme="light"]{--bg:#eef1f3;--panel:#f8fafb;--panel2:#fff;--ink:#1d252b;--muted:#5d6870;--line:#aeb7bd;--cyan:#006f8c;--mag:#a51458;--amber:#8d6200;--green:#27784e;--shadow:0 14px 42px rgba(45,55,62,.14)}html[data-game-theme="light"] .topbar,html[data-game-theme="light"] .controls{background:#e1e6e9!important;color:#475159!important}html[data-game-theme="light"] .card,html[data-game-theme="light"] .screen,html[data-game-theme="light"] .sidebar,html[data-game-theme="light"] .feature,html[data-game-theme="light"] .statement,html[data-game-theme="light"] .event,html[data-game-theme="light"] .side,html[data-game-theme="light"] .legend,html[data-game-theme="light"] .scorebox,html[data-game-theme="light"] .conclusion,html[data-game-theme="light"] .comparebox{background:#f8fafb!important;color:#1d252b!important;border-color:#aeb7bd!important}html[data-game-theme="light"] .option{background:#fff!important;color:#1d252b!important;border-color:#aeb7bd!important}html[data-game-theme="light"] .copy,html[data-game-theme="light"] .subtitle,html[data-game-theme="light"] .screenhead p,html[data-game-theme="light"] .feature p,html[data-game-theme="light"] .statement p,html[data-game-theme="light"] .event p{color:#364149!important}html[data-game-theme="light"] .meta,html[data-game-theme="light"] .option small,html[data-game-theme="light"] .tag{color:#5d6870!important}html[data-game-theme="light"] .network,html[data-game-theme="light"] .plot{background:#e9eef1!important}`}
function frame(){return document.getElementById('caseframe')}
function markCase(d){d.querySelectorAll('.action-required').forEach(x=>x.classList.remove('action-required'));let t=d.querySelector('.prompt')||d.querySelector('.option.focused');if(!t&&d.querySelector('.report'))t=d.querySelector('.option');if(t)t.classList.add('action-required')}
function patchFrame(){const f=frame();if(!f)return;try{const d=f.contentDocument;if(!d||!d.head)return;let s=d.getElementById('music-interaction-layer');if(!s){s=d.createElement('style');s.id='music-interaction-layer';s.textContent=innerCSS();d.head.appendChild(s)}d.documentElement.dataset.gameTheme=theme;markCase(d);const st=d.getElementById('stage');if(st&&!st.__musicGuide){st.__musicGuide=new MutationObserver(()=>{markCase(d);if(tour)refreshTourTarget()});st.__musicGuide.observe(st,{childList:true,subtree:true})}if(!d.__musicGuideInput){d.__musicGuideInput=true;const later=()=>setTimeout(()=>{markCase(d);if(tour)refreshTourTarget()},0);d.addEventListener('keydown',later);d.addEventListener('click',later);d.addEventListener('pointerup',later)}}catch(e){}}
function applyTheme(){document.documentElement.dataset.theme=theme;themeBtn.textContent=theme==='dark'?'☀ Φωτεινό':'☾ Σκοτεινό';document.documentElement.style.colorScheme=theme;let s=document.getElementById('hubLightTheme');if(!s){s=document.createElement('style');s.id='hubLightTheme';s.textContent=`html[data-theme="light"]{--bg:#eef1f3;--panel:#f8fafb;--ink:#1d252b;--muted:#5d6870;--line:#aeb7bd;--cyan:#006f8c;--mag:#a51458;--amber:#8d6200;--green:#27784e}html[data-theme="light"] body{background:radial-gradient(circle at 15% 5%,#fff,#eef1f3 48%,#e5eaed)!important}html[data-theme="light"] .top,html[data-theme="light"] .profile,html[data-theme="light"] .case,html[data-theme="light"] .footer,html[data-theme="light"] .playerbar{background:#f8fafb!important;color:#1d252b!important;border-color:#aeb7bd!important}html[data-theme="light"] .case p,html[data-theme="light"] .intro{color:#3c474f!important}html[data-theme="light"] .btn,html[data-theme="light"] .pbtn{background:#fff!important;color:#1d252b!important;border-color:#8d979f!important}`;document.head.appendChild(s)}patchFrame()}
themeBtn.onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,theme);applyTheme()};
function clearTargets(){document.querySelectorAll('.tour-target-parent').forEach(x=>x.classList.remove('tour-target-parent'));try{frame()?.contentDocument?.querySelectorAll('.tour-target-inner').forEach(x=>x.classList.remove('tour-target-inner'))}catch(e){}}
function targetFor(s){if(s.where==='parent')return document.querySelector(s.sel);try{return frame()?.contentDocument?.querySelector(s.sel)}catch(e){return null}}
function refreshTourTarget(){if(!tour)return;clearTargets();const s=tour[step],t=targetFor(s);if(t)t.classList.add(s.where==='parent'?'tour-target-parent':'tour-target-inner')}
function tourSteps(){const inCase=!document.getElementById('player')?.classList.contains('hidden');if(inCase)return[{where:'inner',sel:'.prompt,.option.focused',title:'Κόκκινο = επόμενη ενέργεια',text:'Το κόκκινο περίγραμμα δείχνει πού περιμένει ενέργεια το παιχνίδι. Πάτησε Enter/Επιλογή για να συνεχίσεις.'},{where:'parent',sel:'.playerbar',title:'Πλοήγηση υπόθεσης',text:'Από εδώ επιστρέφεις στην κεντρική οθόνη, επανεκκινείς ή περνάς στην επόμενη υπόθεση.'},{where:'parent',sel:'#gameTools',title:'Οδηγός και εμφάνιση',text:'Ο οδηγός μπορεί να ξανανοίξει οποιαδήποτε στιγμή. Δίπλα του αλλάζεις Light/Dark.'}];const arr=[{where:'parent',sel:'.case:not(:disabled)',title:'Διάλεξε υπόθεση',text:'Ξεκίνα από την πρώτη διαθέσιμη υπόθεση. Οι επόμενες ξεκλειδώνουν καθώς ολοκληρώνεις τη σεζόν.'},{where:'parent',sel:'#gameTools',title:'Οδηγός και εμφάνιση',text:'Από εδώ ξαναβλέπεις το onboarding και αλλάζεις Light/Dark theme.'}];const q=document.querySelector('.desktop-qr');if(q&&getComputedStyle(q).display!=='none')arr.push({where:'parent',sel:'.desktop-qr',title:'Παίξε στο κινητό',text:'Σκάναρε το QR για να ανοίξεις το ίδιο Season Hub στο κινητό.'});return arr}
function showStep(){if(!tour)return;refreshTourTarget();let b=document.getElementById('tourBox');if(!b){b=document.createElement('div');b.id='tourBox';b.className='tour-box';document.body.appendChild(b)}const s=tour[step];b.innerHTML=`<strong>${s.title}</strong><div>${s.text}</div><span class="tour-count">${step+1} / ${tour.length}</span><div class="tour-actions"><button id="tourSkip">Παράλειψη</button><button class="next" id="tourNext">${step===tour.length-1?'Τέλος':'Επόμενο'}</button></div>`;document.getElementById('tourSkip').onclick=endTour;document.getElementById('tourNext').onclick=()=>{if(step<tour.length-1){step++;showStep()}else endTour()}}
function startTour(){tour=tourSteps();step=0;showStep()}function endTour(){clearTargets();document.getElementById('tourBox')?.remove();tour=null;localStorage.setItem(TOUR_KEY,'1')}document.getElementById('tourBtn').onclick=startTour;
const f=frame();if(f)f.addEventListener('load',()=>{setTimeout(()=>{patchFrame();if(!localStorage.getItem(TOUR_KEY)&&!document.getElementById('player')?.classList.contains('hidden'))startTour()},180)});
new MutationObserver(()=>{patchFrame()}).observe(document.body,{childList:true,subtree:true});applyTheme();setTimeout(()=>{if(!localStorage.getItem(TOUR_KEY))startTour()},600);
})();